// webapp/src/lib/components/game/GameControls.svelte
<script lang="ts">
  import { API_ROOT_URL, SKIP_VALUE } from 'src/config';
  import { generateUserHeaders } from 'src/stores/player';
  import { CardState, TurnAction, type PlayerGame } from 'src/types/Game';
  import { prevent_default } from 'svelte/internal';

  export let game: PlayerGame;
  const roundIndex = game.roundNumber - 1;
  const playCard = (cardId: string) => {
    fetch(`${API_ROOT_URL}/games/${game.id}/turn`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...generateUserHeaders() },
      body: JSON.stringify({
        action: TurnAction[TurnAction.Card],
        cardId
      })
    });
  };

  const placeBid = (bid: number) => {
    fetch(`${API_ROOT_URL}/games/${game.id}/turn`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...generateUserHeaders() },
      body: JSON.stringify({
        action: TurnAction[TurnAction.Bid],
        bid
      })
    });
  };

  const flipCard = (targetPlayerIndex: number) => {
    fetch(`${API_ROOT_URL}/games/${game.id}/turn`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...generateUserHeaders() },
      body: JSON.stringify({
        action: TurnAction[TurnAction.Flip],
        targetPlayerIndex
      })
    });
  };
</script>

<div>
  <div>
    <h3>Play Card</h3>
    <div>
      {#each game.playerCards as card (card.id)}
        <button
          on:click={() => playCard(card.id)}
          disabled={card.state === CardState.Discarded ||
            game.activePlayerIndex !== game.playerIndex ||
            game.playerRoundCardIdsPlayed[roundIndex].includes(card.id)}
          >{card.type}</button
        >
      {/each}
    </div>
    <h3>Place Bid</h3>
    <div>
      <button
        on:click={() => placeBid(SKIP_VALUE)}
        disabled={game.activePlayerIndex !== game.playerIndex}>Withdraw</button
      >
      {#each Array.from({ length: game.roundCountPlayerCardsPlayed[roundIndex].reduce((prev, curr) => prev + curr, 1) }, (v, i) => i) as bidNumber}
        <button
          on:click={() => placeBid(bidNumber)}
          disabled={game.activePlayerIndex !== game.playerIndex}
          >{bidNumber}</button
        >
      {/each}
    </div>
    <h3>Flip Cards</h3>
    <div>
      {#each Array.from({ length: game.playerCount }, (v, i) => i) as targetPlayerIndex}
        <button
          on:click={() => flipCard(targetPlayerIndex)}
          disabled={game.activePlayerIndex !== game.playerIndex}
          >{game.playerNicknames[targetPlayerIndex]} ({targetPlayerIndex})</button
        >
      {/each}
    </div>
  </div>
</div>

// webapp/src/components/game/GameControlsComponent.tsx
import { Button } from "@mui/material";
import { useState } from "react";
import { API_ROOT_URL, USER_ID, USER_ID_HEADER, USER_SECRET, USER_SECRET_HEADER } from "../../config";
import { CardState, CardType, PlayerGame, RoundPhase, TurnAction } from "../../models/Game";

const SKIP_VALUE = -1;

export function GameControlsComponent({ game }: { game: PlayerGame }) {
  const roundIndex = game.roundNumber - 1;
  
  const [clicked, setClicked] = useState(false);

  const playCard = (cardId: string) => {
    setClicked(true);
    fetch(`${API_ROOT_URL}/games/${game.id}/turn`, 
      { 
        method: "POST",
        headers: { "Content-Type": "application/json", [USER_ID_HEADER]: USER_ID, [USER_SECRET_HEADER]: USER_SECRET  },
        body: JSON.stringify({
          action: TurnAction[TurnAction.Card],
          cardId
        })
      })
      .finally(() => setClicked(false))
  }

  const placebid = (bid: number) => {
    setClicked(true);
    fetch(`${API_ROOT_URL}/games/${game.id}/turn`, 
      { 
        method: "POST",
        headers: { "Content-Type": "application/json", [USER_ID_HEADER]: USER_ID, [USER_SECRET_HEADER]: USER_SECRET  },
        body: JSON.stringify({
          action: TurnAction[TurnAction.Bid],
          bid
        })
      })
      .finally(() => setClicked(false))
  }
  
  const flipCard = (targetPlayerIndex: number) => {
    setClicked(true);
    fetch(`${API_ROOT_URL}/games/${game.id}/turn`, 
      { 
        method: "POST",
        headers: { "Content-Type": "application/json", [USER_ID_HEADER]: USER_ID, [USER_SECRET_HEADER]: USER_SECRET  },
        body: JSON.stringify({
          action: TurnAction[TurnAction.Flip],
          targetPlayerIndex
        })
      })
      .finally(() => setClicked(false))
  }

  const maxBid = game.roundCountPlayerCardsPlayed[roundIndex].reduce((c, cc) => c + cc, 0);
  const minBid = Math.max(...game.currentBids) + 1;

  const arrayOfValues = [];
  for (let i = minBid; i <= maxBid; i++) {
    arrayOfValues.push(i);
  }

  const cardButtons = game.playerCards.map(card => {
    return <Button
    key={card.id}
    onClick={() => playCard(card.id)}
    color={card.state === CardState.Discarded ? "error" : "primary"}
    disabled={
      ![RoundPhase.PlayFirstCards, RoundPhase.PlayCards].includes(game.currentRoundPhase) || 
      clicked || game.activePlayerIndex !== game.playerIndex || 
      card.state === CardState.Discarded || 
      game.playerRoundCardIdsPlayed[roundIndex].includes(card.id)
    }
    >
      Play {CardType[card.type]}
    </Button>
  })

  const bidControls = <><Button 
      disabled={clicked || game.activePlayerIndex !== game.playerIndex || game.currentRoundPhase === RoundPhase.PlayFirstCards || minBid === 1} 
      onClick={() => placebid(SKIP_VALUE)}>Retire</Button>
    {//This is a completely terrible UI 
    arrayOfValues.map((bidNumber, i) => {
      return <Button key={i}
      disabled={clicked || game.activePlayerIndex !== game.playerIndex  || game.currentRoundPhase === RoundPhase.PlayFirstCards} 
      onClick={() => placebid(bidNumber)}>Bid {bidNumber}</Button>
    })
    }</>
  
  const flipButtons = game.roundCountPlayerCardsPlayed[roundIndex].map((playedCount, i) => {
      return <Button
      key={i}
      onClick={() => flipCard(i)}
      disabled={
        clicked ||
        (i !== game.activePlayerIndex && game.roundPlayerCardsRevealed[roundIndex][game.activePlayerIndex].length !== playedCount) ||
        playedCount === game.roundPlayerCardsRevealed[roundIndex][i].length
      }
      >
        Flip Player {i}
      </Button>
    })

  if (game.currentRoundPhase !== RoundPhase.Flipping) {
    return <>{cardButtons}{bidControls}</>
  }
  return <>{flipButtons}</>;
}
